- id: check-classifiers
  name: Check classifiers for license specification
  entry: checkclassifiers
  language: python
  files: '^pyproject.toml$'
  types: [toml]
- id: check-license-glob
  name: Check that license file globs match a file in the repo
  entry: checklicenseglob
  language: python
  files: '^pyproject.toml$'
  types: [toml]
